%% Excel Plot Script
%   Riley "Actual badass" Waite
%   May 2017
%   Rose-Hulman Institute of Technology
%
%
%   This script will dynamically plot 3d meshes generated by the Riley's
%   equally badass Sketch3D_To_Excel VB macro in Solidworks.
%
%   This will ideally be used, eventually, as a GUI for coupled 
%   moment chassis torsional stiffness FEA

%% Clean Up
clear variables
close all

%% Parameters
DataFile = 'Chassis Nodes.xlsx';

%% Importing data from xlsx

% Points
[temp,~] = xlsread(DataFile, 'B:B'); % Columns in points list
l = length(temp); % Number of points

pts = xlsread(DataFile,['B4:D',num2str(l+3)]);

% Lines
[temp,~] = xlsread(DataFile, 'F:F'); % Columns in lines list
l = length(temp); % Number of lines

lineStart = [xlsread(DataFile,['F4:H',num2str(l+3)])];
lineEnd = [xlsread(DataFile,['I4:K',num2str(l+3)])];

clear l temp

%% Error checking data grab
if length(lineStart) ~= length(lineEnd)
    error('Uneven number of line beginning and eng coordinates. This shouldn''t even happen. Something''s gone horribly wrong; check Excel file');
end

if (size(pts(:,1),1) ~= size(pts(:,2),1)) || (size(pts(:,2),1) ~= size(pts(:,3),1))
    error('Uneven coordinate count in point cartesians. This shouldn''t even happen. Something''s gone horribly wrong; check Excel file');
end

%% Plotting in 3D
f = figure;
hold on
rotate3d on

daspect([1 1 1])

scatter3(pts(:,1),pts(:,2),pts(:,3))
for i = 1:length(lineStart)
    plot3([lineStart(i,1),lineEnd(i,1)],[lineStart(i,2),lineEnd(i,2)],[lineStart(i,3),lineEnd(i,3)])
end

axis vis3d